# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# User specific aliases and functions
alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'

export LANG=ja_JP.UTF-8
